# Generated by Django 5.0.1 on 2024-01-21 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="user2",
        ),
        migrations.DeleteModel(
            name="FriendRequest",
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
