# Generated by Django 5.0.1 on 2024-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network_app", "0003_customuser_friends_friendrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(
                default=[], related_name="friends", to="social_network_app.customuser"
            ),
        ),
    ]
